[mgr]
show_hidden = true
sort_by = "alphabetical"
sort_sensitive = false
linemode = "size"

[preview]
max_width = 5000
max_height = 3500

[opener]
edit = [
  { run = "nvim %s", block = true, for = "unix" },
]

[open]
prepend_rules = [
  { mime = "text/*", use = "edit" },
  { url = "*.nix", use = "edit" },
  { url = "*.lua", use = "edit" },
  { url = "*.toml", use = "edit" },
  { url = "*.md", use = "edit" },
]
